"""added foreign key utilisateur_id to RDV

Revision ID: 23155ee74701
Revises: e95eaa21397a
Create Date: 2025-07-02 16:29:38.757277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23155ee74701'
down_revision = 'e95eaa21397a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('utilisateur_id')

    # ### end Alembic commands ###
