"""added province and commune to RDV

Revision ID: 393395dbe9e4
Revises: 23155ee74701
Create Date: 2025-07-02 20:39:28.428805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393395dbe9e4'
down_revision = '23155ee74701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('commune', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.drop_column('commune')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
