"""empty message

Revision ID: 48d5adbd40c0
Revises: b3794765d4a6
Create Date: 2025-07-02 16:02:54.991122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d5adbd40c0'
down_revision = 'b3794765d4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hopital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hopital', ['hopital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hopital_id')

    # ### end Alembic commands ###
