"""added forgotten sexe column

Revision ID: 6db553c43005
Revises: b2186ad9680f
Create Date: 2025-06-26 08:50:37.087252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db553c43005'
down_revision = 'b2186ad9680f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexe', sa.String(length=1), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('sexe')

    # ### end Alembic commands ###
