"""Removed unnecessary and complicated foreign  keys

Revision ID: 6dbaba2ed34d
Revises: de71812a3a6d
Create Date: 2025-07-02 14:55:19.287237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dbaba2ed34d'
down_revision = 'de71812a3a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur_service_hopital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rdv_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('utilisateur_service_hopital_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('utilisateur_service_hopital_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rdv', ['rdv_id'], ['id'])
        batch_op.drop_column('hopital_id')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur_service_hopital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hopital_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('utilisateur_service_hopital_ibfk_1'), 'hopital', ['hopital_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('utilisateur_service_hopital_ibfk_2'), 'service', ['service_id'], ['id'])
        batch_op.drop_column('rdv_id')

    # ### end Alembic commands ###
