"""added table 'service' to the DB

Revision ID: 86239899c61e
Revises: e88814c8b4b3
Create Date: 2025-06-29 18:04:26.708349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86239899c61e'
down_revision = 'e88814c8b4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###
