"""modified the way foreign keys are created and added join table

Revision ID: 9f1168e8ee9c
Revises: e622d927b32b
Create Date: 2025-06-30 19:25:05.024251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1168e8ee9c'
down_revision = 'e622d927b32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hopital',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('service_hopital',
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('hopital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hopital_id'], ['hopital.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_hopital')
    op.drop_table('hopital')
    # ### end Alembic commands ###
