"""restored email and numeroTelephone to be nullable

Revision ID: b2186ad9680f
Revises: 35ce23b69fe1
Create Date: 2025-06-24 23:00:32.559735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2186ad9680f'
down_revision = '35ce23b69fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)
        batch_op.alter_column('numeroTelephone',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('numeroTelephone',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)

    # ### end Alembic commands ###
