"""empty message

Revision ID: b3794765d4a6
Revises: 6dbaba2ed34d
Create Date: 2025-07-02 14:59:28.138795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3794765d4a6'
down_revision = '6dbaba2ed34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
